# environment.yml

name: DataStorm
channels:
  - conda-forge
  - defaults
dependencies:
  - _libavif_api=1.1.1=h57928b3_3
  - _openmp_mutex=4.5=2_gnu
  - aom=3.9.1=he0c23c2_0
  - brotli=1.2.0=h2d644bc_1
  - brotli-bin=1.2.0=hfd05255_1
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2025.12.2=haa95532_0
  - cairo=1.18.4=h5782bbf_0
  - contourpy=1.3.3=py312hf90b1b7_3
  - cycler=0.12.1=pyhcf101f3_2
  - dav1d=1.2.1=hcfcfb64_0
  - double-conversion=3.3.1=he0c23c2_0
  - expat=2.7.3=h885b0b7_4
  - ffmpeg=7.1.0=gpl_h1e5d33d_505
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h765892d_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=hc364b38_1
  - fonttools=4.61.1=py312h05f76fc_0
  - freeglut=3.2.2=he0c23c2_3
  - freetype=2.14.1=h57928b3_0
  - fribidi=1.0.16=hfd05255_0
  - gdk-pixbuf=2.42.12=hed59a49_0
  - graphite2=1.3.14=hac47afa_2
  - harfbuzz=11.0.0=h9e37d49_0
  - hdf5=1.14.3=nompi_hb2c4d47_109
  - icu=75.1=he0c23c2_0
  - imath=3.1.12=hbb528cf_0
  - jasper=4.2.8=h8ad263b_0
  - khronos-opencl-icd-loader=2024.10.24=h2466b09_1
  - kiwisolver=1.4.9=py312h78d62e6_2
  - krb5=1.21.3=hdf4eb48_0
  - lcms2=2.17=hbcf6048_0
  - lerc=4.0.0=h6470a55_1
  - libabseil=20240722.0=cxx17_h4eb7d71_4
  - libaec=1.1.4=h20038f6_0
  - libasprintf=0.22.5=h5728263_3
  - libavif16=1.1.1=h4d049a7_2
  - libblas=3.11.0=5_hf2e6a31_mkl
  - libbrotlicommon=1.2.0=hfd05255_1
  - libbrotlidec=1.2.0=hfd05255_1
  - libbrotlienc=1.2.0=hfd05255_1
  - libcblas=3.11.0=5_h2a3cdd5_mkl
  - libclang13=21.1.7=default_ha2db4b5_2
  - libcurl=8.17.0=h43ecb02_1
  - libdeflate=1.22=h2466b09_0
  - libexpat=2.7.3=h885b0b7_4
  - libffi=3.4.4=hd77b12b_1
  - libfreetype=2.14.1=h57928b3_0
  - libfreetype6=2.14.1=hdbac1cb_0
  - libgcc=15.2.0=h8ee18e1_16
  - libgettextpo=0.22.5=h5728263_3
  - libglib=2.84.0=h7025463_0
  - libgomp=15.2.0=h8ee18e1_16
  - libhwloc=2.12.1=default_h88281d1_1000
  - libiconv=1.18=hc1393d2_2
  - libintl=0.22.5=h5728263_3
  - libjpeg-turbo=3.1.2=hfd05255_0
  - liblapack=3.11.0=5_hf9ab0e9_mkl
  - liblapacke=3.11.0=5_h3ae206f_mkl
  - libopencv=4.11.0=qt6_py312h8c2cf4d_602
  - libopenvino=2025.0.0=hb1d9b14_2
  - libopenvino-auto-batch-plugin=2025.0.0=h04f32e0_2
  - libopenvino-auto-plugin=2025.0.0=h04f32e0_2
  - libopenvino-hetero-plugin=2025.0.0=hb61b842_2
  - libopenvino-intel-cpu-plugin=2025.0.0=hb1d9b14_2
  - libopenvino-intel-gpu-plugin=2025.0.0=hb1d9b14_2
  - libopenvino-ir-frontend=2025.0.0=hb61b842_2
  - libopenvino-onnx-frontend=2025.0.0=h6e6c283_2
  - libopenvino-paddle-frontend=2025.0.0=h6e6c283_2
  - libopenvino-pytorch-frontend=2025.0.0=he0c23c2_2
  - libopenvino-tensorflow-frontend=2025.0.0=ha83d810_2
  - libopenvino-tensorflow-lite-frontend=2025.0.0=he0c23c2_2
  - libopus=1.6=h6a83c73_0
  - libpng=1.6.53=h7351971_0
  - libprotobuf=5.28.3=h8309712_1
  - librsvg=2.58.4=h5ce5fed_3
  - libsqlite=3.51.1=hf5d6505_1
  - libssh2=1.11.1=h9aa295b_0
  - libtiff=4.7.0=hfc51747_1
  - libwebp-base=1.6.0=h4d5522a_0
  - libwinpthread=12.0.0.r4.gg4f2fc60ca=h57928b3_10
  - libxcb=1.17.0=h0e4246c_0
  - libxml2=2.13.9=h741aa76_0
  - libxslt=1.1.43=h25c3957_0
  - libzlib=1.3.1=h02ab6af_0
  - llvm-openmp=21.1.8=h4fa8253_0
  - matplotlib=3.10.8=py312h2e8e312_0
  - matplotlib-base=3.10.8=py312h0ebf65c_0
  - mkl=2025.3.0=hac47afa_454
  - munkres=1.1.4=pyhd8ed1ab_1
  - numpy=2.4.0=py312ha72d056_0
  - opencl-headers=2025.06.13=he0c23c2_0
  - opencv=4.11.0=qt6_py312h54cea10_602
  - openexr=3.3.2=h974021d_0
  - openh264=2.5.0=ha9db3cd_0
  - openjpeg=2.5.3=h24db6dd_1
  - openssl=3.6.0=h725018a_0
  - packaging=25.0=pyh29332c3_1
  - pandas=2.3.3=py312hc128f0a_2
  - pango=1.56.3=h0c53d3b_1
  - pcre2=10.44=h99c9b8b_2
  - pillow=11.3.0=py312h5ee8bfe_3
  - pip=25.3=pyhc872135_0
  - pixman=0.46.4=h5112557_1
  - pthread-stubs=0.4=h0e40799_1002
  - pugixml=1.15=h372dad0_0
  - py-opencv=4.11.0=qt6_py312h53463f2_602
  - pyparsing=3.2.5=pyhcf101f3_0
  - pyside6=6.8.3=py312h2ee7485_0
  - python=3.12.12=h716150d_1
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-tzdata=2025.3=pyhd8ed1ab_0
  - python_abi=3.12=3_cp312
  - pytz=2025.2=pyhd8ed1ab_0
  - qhull=2020.2=hc790b64_5
  - qt6-main=6.8.3=h72a539a_1
  - rav1e=0.6.6=h975169c_2
  - setuptools=80.9.0=py312haa95532_0
  - six=1.17.0=pyhe01879c_1
  - snappy=1.2.2=h7fa0ca8_1
  - sqlite=3.51.0=hda9a48d_0
  - svt-av1=2.3.0=he0c23c2_0
  - tbb=2022.3.0=hd094cb3_1
  - tk=8.6.15=hf199647_0
  - tornado=6.5.4=py312he06e257_0
  - tzdata=2025b=h04d1e81_0
  - ucrt=10.0.22621.0=haa95532_0
  - unicodedata2=17.0.0=py312he06e257_1
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wheel=0.45.1=py312haa95532_0
  - x264=1!164.3095=h8ffe710_2
  - x265=3.5=h2d74725_3
  - xorg-libxau=1.0.12=hba3369d_1
  - xorg-libxdmcp=1.1.5=hba3369d_1
  - xz=5.6.4=h4754444_1
  - zlib=1.3.1=h02ab6af_0
  - zstd=1.5.7=h534d264_6
  - pip:
      - absl-py==2.3.1
      - cffi==2.0.0
      - flatbuffers==25.12.19
      - mediapipe==0.10.31
      - pycparser==2.23
      - sounddevice==0.5.3
prefix: C:\Anaconda\envs\DataStorm
